config/routes.rb
Rails.application.routes.draw do
  resources :drug_administrations
  resources :medication_drugs
  resources :medications
  resources :drugs
  get 'static_pages/index'

  resources :blood_pressures
  resources :blood_groups
  resources :pulses
  resources :temperatures
  resources :patients
  
  root 'static_pages#index'
  
  get '/patients/:id/filter', to: 'patients#show'

  
  
  

end

app/models/drug.rb
class Drug < ActiveRecord::Base
    # has_many :medication_drugs
    belongs_to :medication_drugs
    validates :drug, :presence => true
end

app/controllers/drugs_controller.rb
class DrugsController < ApplicationController
  before_action :set_drug, only: [:show, :edit, :update, :destroy]

  # GET /drugs
  # GET /drugs.json
  def index
    @drugs = Drug.all
  end

  # GET /drugs/1
  # GET /drugs/1.json
  def show
  end

  # GET /drugs/new
  def new
    @drug = Drug.new
  end

  # GET /drugs/1/edit
  def edit
  end

  # POST /drugs
  # POST /drugs.json
  def create
    @drug = Drug.new(drug_params)

    respond_to do |format|
      if @drug.save
        format.html { redirect_to @drug, notice: 'Drug was successfully created.' }
        format.json { render :show, status: :created, location: @drug }
      else
        format.html { render :new }
        format.json { render json: @drug.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drugs/1
  # PATCH/PUT /drugs/1.json
  def update
    respond_to do |format|
      if @drug.update(drug_params)
        format.html { redirect_to @drug, notice: 'Drug was successfully updated.' }
        format.json { render :show, status: :ok, location: @drug }
      else
        format.html { render :edit }
        format.json { render json: @drug.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drugs/1
  # DELETE /drugs/1.json
  def destroy
    @drug.destroy
    respond_to do |format|
      format.html { redirect_to drugs_url, notice: 'Drug was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_drug
      @drug = Drug.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def drug_params
      params.require(:drug).permit(:drug, :adult24HourDose, :otherDose, :otherDoseHours)
    end
end

app/helpers/drugs_helper.rb
module DrugsHelper
end

app/views/drugs/_form.html.erb
<%= form_for(@drug) do |f| %>
  <% if @drug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@drug.errors.count, "error") %> prohibited this drug from being saved:</h2>

      <ul>
      <% @drug.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :drug %><br>
    <%= f.text_field :drug %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/drugs/edit.html.erb
<h1>Editing Drug</h1>

<%= render 'form' %>

<%= link_to 'Show', @drug %> |
<%= link_to 'Back', drugs_path %>

app/views/drugs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Drugs</h1>

<table>
  <thead>
    <tr>
      <th>Drug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drugs.each do |drug| %>
      <tr>
        <td><%= drug.drug %></td>
        <td><%= link_to 'Show', drug %></td>
        <td><%= link_to 'Edit', edit_drug_path(drug) %></td>
        <td><%= link_to 'Destroy', drug, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Drug', new_drug_path %>

app/views/drugs/new.html.erb
<h1>New Drug</h1>

<%= render 'form' %>

<%= link_to 'Back', drugs_path %>

app/views/drugs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Drug:</strong>
  <%= @drug.drug %>
</p>

<%= link_to 'Edit', edit_drug_path(@drug) %> |
<%= link_to 'Back', drugs_path %>