config/routes.rb
Rails.application.routes.draw do
  resources :drug_administrations
  resources :medication_drugs
  resources :medications
  resources :drugs
  get 'static_pages/index'

  resources :blood_pressures
  resources :blood_groups
  resources :pulses
  resources :temperatures
  resources :patients
  
  root 'static_pages#index'
  
  get '/patients/:id/filter', to: 'patients#show'

  
  
  

end

app/models/blood_pressure.rb
class BloodPressure < ActiveRecord::Base
    validates :patient_id, :presence => true
    validates :systolic, :presence => true
    validates :diastolic, :presence => true
    belongs_to :patient
end

app/controllers/blood_pressures_controller.rb
class BloodPressuresController < ApplicationController
  before_action :set_blood_pressure, only: [:show, :edit, :update, :destroy]

  # GET /blood_pressures
  # GET /blood_pressures.json
  def index
    # @blood_pressures = BloodPressure.all
    @blood_pressures = params[:patient].present? ? BloodPressure.all.where(patient_id: params[:patient]) : BloodPressure.all
  end

  # GET /blood_pressures/1
  # GET /blood_pressures/1.json
  def show
  end

  # GET /blood_pressures/new
  def new
     @patient = params[:patient].present? ? params[:patient] : ''
    @blood_pressure = BloodPressure.new
  end

  # GET /blood_pressures/1/edit
  def edit
  end

  # POST /blood_pressures
  # POST /blood_pressures.json
  def create
    @blood_pressure = BloodPressure.new(blood_pressure_params)

    respond_to do |format|
      if @blood_pressure.save
        format.html { redirect_to @blood_pressure, notice: 'Blood pressure was successfully created.' }
        format.json { render :show, status: :created, location: @blood_pressure }
      else
        format.html { render :new }
        format.json { render json: @blood_pressure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blood_pressures/1
  # PATCH/PUT /blood_pressures/1.json
  def update
    respond_to do |format|
      if @blood_pressure.update(blood_pressure_params)
        format.html { redirect_to @blood_pressure, notice: 'Blood pressure was successfully updated.' }
        format.json { render :show, status: :ok, location: @blood_pressure }
      else
        format.html { render :edit }
        format.json { render json: @blood_pressure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blood_pressures/1
  # DELETE /blood_pressures/1.json
  def destroy
    @blood_pressure.destroy
    respond_to do |format|
      format.html { redirect_to blood_pressures_url, notice: 'Blood pressure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blood_pressure
      @blood_pressure = BloodPressure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blood_pressure_params
      params.require(:blood_pressure).permit(:patient_id, :systolic, :diastolic, :dt)
    end
end

app/helpers/blood_pressures_helper.rb
module BloodPressuresHelper
end

app/views/blood_pressures/_form.html.erb
<%= form_for(@blood_pressure) do |f| %>
  <% if @blood_pressure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blood_pressure.errors.count, "error") %> prohibited this blood_pressure from being saved:</h2>

      <ul>
      <% @blood_pressure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :patient_id %><br>
    <%= collection_select(:blood_pressure, :patient_id, Patient.all, :id, :fullname, selected: @patient, prompt: true) %>
  </div>
  <div class="field">
    <%= f.label :systolic %><br>
    <%= f.number_field :systolic %>
  </div>
  <div class="field">
    <%= f.label :diastolic %><br>
    <%= f.number_field :diastolic %>
  </div>
  <div class="field">
    <%= f.label :dt %><br>
    <%= f.datetime_select :dt %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blood_pressures/edit.html.erb
<h1>Editing Blood Pressure</h1>

<%= render 'form' %>

<%= link_to 'Show', @blood_pressure %> |
<%= link_to 'Back', blood_pressures_path %>

app/views/blood_pressures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Blood Pressures</h1>

<table>
  <thead>
    <tr>
      <th>Patient</th>
      <th>Systolic</th>
      <th>Diastolic</th>
      <th>Dt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blood_pressures.each do |blood_pressure| %>
      <tr>
        <td><%= Patient.find(blood_pressure.patient_id).fullname %></td>
        <td><%= blood_pressure.systolic %></td>
        <td><%= blood_pressure.diastolic %></td>
        <td><%= blood_pressure.dt %></td>
        <td><%= link_to 'Show', blood_pressure %></td>
        <td><%= link_to 'Edit', edit_blood_pressure_path(blood_pressure) %></td>
        <td><%= link_to 'Destroy', blood_pressure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blood pressure', new_blood_pressure_path %>

app/views/blood_pressures/new.html.erb
<h1>New Blood Pressure</h1>

<%= render 'form' %>

<%= link_to 'Back', blood_pressures_path %>

app/views/blood_pressures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Patient:</strong>
  <%= Patient.find(@blood_pressure.patient_id).fullname %>
</p>

<p>
  <strong>Systolic:</strong>
  <%= @blood_pressure.systolic %>
</p>

<p>
  <strong>Diastolic:</strong>
  <%= @blood_pressure.diastolic %>
</p>

<p>
  <strong>Dt:</strong>
  <%= @blood_pressure.dt %>
</p>

<%= link_to 'Edit', edit_blood_pressure_path(@blood_pressure) %> |
<%= link_to 'Back', blood_pressures_path %> |
<%= link_to 'To Patient', ('/patients/' + @pulse.patient_id.to_s) %>