config/routes.rb
Rails.application.routes.draw do
  resources :drug_administrations
  resources :medication_drugs
  resources :medications
  resources :drugs
  get 'static_pages/index'

  resources :blood_pressures
  resources :blood_groups
  resources :pulses
  resources :temperatures
  resources :patients
  
  root 'static_pages#index'
  
  get '/patients/:id/filter', to: 'patients#show'

  
  
  

end

app/models/medication_drug.rb
class MedicationDrug < ActiveRecord::Base
    # belongs_to :medication
    # belongs_to :drug
    has_many :medication
    has_many :drug
    validates :medication_id, :presence => true
    validates :drug_id, :presence => true
    validates :drugMg, :presence => true
    validates :drugMl, :presence => true
end

app/controllers/medication_drugs_controller.rb
class MedicationDrugsController < ApplicationController
  before_action :set_medication_drug, only: [:show, :edit, :update, :destroy]

  # GET /medication_drugs
  # GET /medication_drugs.json
  def index
    @medication_drugs = MedicationDrug.all
  end

  # GET /medication_drugs/1
  # GET /medication_drugs/1.json
  def show
  end

  # GET /medication_drugs/new
  def new
    @medication_drug = MedicationDrug.new
  end

  # GET /medication_drugs/1/edit
  def edit
  end

  # POST /medication_drugs
  # POST /medication_drugs.json
  def create
    @medication_drug = MedicationDrug.new(medication_drug_params)

    respond_to do |format|
      if @medication_drug.save
        format.html { redirect_to @medication_drug, notice: 'Medication drug was successfully created.' }
        format.json { render :show, status: :created, location: @medication_drug }
      else
        format.html { render :new }
        format.json { render json: @medication_drug.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medication_drugs/1
  # PATCH/PUT /medication_drugs/1.json
  def update
    respond_to do |format|
      if @medication_drug.update(medication_drug_params)
        format.html { redirect_to @medication_drug, notice: 'Medication drug was successfully updated.' }
        format.json { render :show, status: :ok, location: @medication_drug }
      else
        format.html { render :edit }
        format.json { render json: @medication_drug.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medication_drugs/1
  # DELETE /medication_drugs/1.json
  def destroy
    @medication_drug.destroy
    respond_to do |format|
      format.html { redirect_to medication_drugs_url, notice: 'Medication drug was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medication_drug
      @medication_drug = MedicationDrug.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medication_drug_params
      params.require(:medication_drug).permit(:medication_id, :drug_id, :drugMg, :drugMl, :format)
    end
end

app/helpers/medication_drugs_helper.rb
module MedicationDrugsHelper
end

app/views/medication_drugs/_form.html.erb
<%= form_for(@medication_drug) do |f| %>
  <% if @medication_drug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medication_drug.errors.count, "error") %> prohibited this medication_drug from being saved:</h2>

      <ul>
      <% @medication_drug.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <!--<div class="field">-->
  <!--  <%= f.label :medication_id %><br>-->
  <!--  <%= f.number_field :medication_id %>-->
  <!--</div>-->
  <div class="field">
    <%= f.label :medication_id %><br>
    <!--<%= collection_select(:medication_drug, :medication_id, Medication.all, :id, :medication, prompt: true) %>-->
    <%= collection_select(:medication_drug, :medication_id, Medication.all, :id, :formulatedName, prompt: true) %>
  </div>
  
  <div class="field">
    <%= f.label :drug_id %><br>
    <%= collection_select(:medication_drug, :drug_id, Drug.all, :id, :drug, prompt: true) %>
  </div>
  
  <div class="field">
    <%= f.label :drugMg %><br>
    <%= f.text_field :drugMg %>
  </div>
  <div class="field">
    <%= f.label :drugMl %><br>
    <%= f.text_field :drugMl %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/medication_drugs/edit.html.erb
<h1>Editing Medication Drug</h1>

<%= render 'form' %>

<%= link_to 'Show', @medication_drug %> |
<%= link_to 'Back', medication_drugs_path %>

app/views/medication_drugs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Medication Drugs</h1>

<table>
  <thead>
    <tr>
      <th>Medication</th>
      <th>Drug</th>
      <th>Drugmg</th>
      <th>Drugml</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @medication_drugs.each do |medication_drug| %>
      <tr>
        <td><%= Medication.find(medication_drug.medication_id).medication %></td>
        <td><%= Drug.find(medication_drug.drug_id).drug %></td>
        <td><%= medication_drug.drugMg %></td>
        <td><%= medication_drug.drugMl %></td>
        <td><%= link_to 'Show', medication_drug %></td>
        <td><%= link_to 'Edit', edit_medication_drug_path(medication_drug) %></td>
        <td><%= link_to 'Destroy', medication_drug, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Medication drug', new_medication_drug_path %>

app/views/medication_drugs/new.html.erb
<h1>New Medication Drug</h1>

<%= render 'form' %>

<%= link_to 'Back', medication_drugs_path %>

app/views/medication_drugs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Medication:</strong>
  <%= Medication.find(@medication_drug.medication_id).medication %>
</p>

<p>
  <strong>Drug:</strong>
  <%= Drug.find(@medication_drug.drug_id).drug %>
</p>

<p>
  <strong>Drugmg:</strong>
  <%= @medication_drug.drugMg %>
</p>

<p>
  <strong>Drugml:</strong>
  <%= @medication_drug.drugMl %>
</p>

<%= link_to 'Edit', edit_medication_drug_path(@medication_drug) %> |
<%= link_to 'Back', medication_drugs_path %>